apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: trainschedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: trainschedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trainschedule
      track: stable
  template:
    metadata:
      labels:
        app: trainschedule
        track: stable
    spec:
      containers:
      - name: trainschedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
